config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic.base import TemplateView

from rest_framework.documentation import include_docs_urls

from . import basic_views

urlpatterns = [
    path("", basic_views.HomeView.as_view(), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("profile/", basic_views.ProfileView.as_view(), name="profile"),
    path(
        "gwas/",
        include("locuszoom_plotting_service.gwas.urls", namespace="gwas")
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        "api/v1/",
        include("locuszoom_plotting_service.api.urls", namespace="apiv1"),
    ),
    path(
        "api-docs/",
        include_docs_urls(title='GWAS API Docs')
    ),
    # User management
    path("accounts/", include("config.auth_urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

locuszoom_plotting_service/api/urls.py
"""
Routes for the raw data API
"""

from django.urls import path
from rest_framework.renderers import OpenAPIRenderer
from rest_framework.schemas import get_schema_view

from . import views

schema_view = get_schema_view(title='LocusZoom API', renderer_classes=[OpenAPIRenderer])

app_name = "api"
urlpatterns = [
    path('gwas/', views.GwasListView.as_view(), name='gwas-list'),
    path('gwas/user-all/', views.GwasListViewUnprocessed.as_view(), name='gwas-user-all'),
    path('gwas/<slug>/', views.GwasDetailView.as_view(), name='gwas-metadata'),
    path('gwas/<slug>/data/', views.GwasRegionView.as_view(), name='gwas-region'),
    # "Standardized" api schema; can be used to auto-create api clients.
    path('schema/', schema_view)
]

locuszoom_plotting_service/gwas/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from django.views.generic import RedirectView

from . import views

app_name = 'gwas'
urlpatterns = [
    path('upload/', login_required(views.GwasCreate.as_view()), name='upload'),

    # Dataset-specific views
    path('', RedirectView.as_view(pattern_name='home')),
    path('<slug>/', views.GwasSummary.as_view(), name='overview'),
    path('<slug>/delete/', views.GwasDelete.as_view(), name='delete'),
    path('<slug>/edit/', views.GwasEdit.as_view(), name='edit'),
    path('<slug>/region/', views.GwasRegion.as_view(), name='region'),
    path('<slug>/share/', views.GwasShare.as_view(), name='share'),

    # Temporary debugging views
    path('<slug>/rerun/', views.rerun_analysis, name='rerun'),

    # Some views that serve up raw data from server
    path('<slug>/data/', views.GwasSummaryStats.as_view(), name='gwas-download'),
    path('<slug>/data/ingest_log/', views.GwasIngestLog.as_view(), name='gwas-ingest-log'),
    path('<slug>/data/manhattan/', views.GwasManhattanJson.as_view(), name='manhattan-json'),
    path('<slug>/data/qq/', views.GwasQQJson.as_view(), name='qq-json'),
]

locuszoom_plotting_service/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, SlugField
from django.utils.translation import gettext_lazy as _

from ..base.util import _generate_slug


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    #   around the globe, or among all oauth providers.
    slug = SlugField(max_length=6, unique=True, editable=False, default=_generate_slug,
                     help_text="The external facing identifier for this record")

    name = CharField(_("Name of User"), blank=True, max_length=255)

    # def get_absolute_url(self):
    #     FIXME: Implement a per-user profile page
    #     return reverse("users:detail", kwargs={"username": self.username})

    @property
    def display_name(self):
        """If no name is available, default to the public user ID (slug)"""
        return self.name or self.get_full_name() or self.slug

    def save(self, *args, **kwargs):
        """Generate a slug and ensure it is unique"""
        while True:  # Ensure creation of a random, unique slug
            if self.pk:  # ...but only if the record is new
                break

            slug = _generate_slug()
            if not User.objects.filter(slug=slug).first():
                self.slug = slug
                break

        super().save(*args, **kwargs)

locuszoom_plotting_service/gwas/forms.py
from django import forms

from . import models


class AnalysisInfoForm(forms.ModelForm):
    class Meta:
        model = models.AnalysisInfo
        fields = ('label', 'study_name', 'pmid', 'is_public', 'build',)


class AnalysisFilesetForm(forms.ModelForm):
    class Meta:
        model = models.AnalysisFileset
        fields = ('parser_options', 'raw_gwas_file')


class ViewLinkForm(forms.ModelForm):
    class Meta:
        model = models.ViewLink
        fields = ('label',)

locuszoom_plotting_service/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

locuszoom_plotting_service/api/views.py
import os
import typing as ty

from django.conf import settings
from rest_framework import exceptions as drf_exceptions
from rest_framework import permissions as drf_permissions
from rest_framework import generics
from rest_framework import renderers as drf_renderers

from locuszoom_plotting_service.api.filters import GwasFilter
from locuszoom_plotting_service.gwas import models as lz_models

from zorp.sniffers import guess_gwas_standard

from . import (
    permissions,
    serializers
)


class GwasListView(generics.ListAPIView):
    """
    List all known uploaded GWAS analyses that are available for viewing
        (public data sets, plus any private to just this user)

    This excludes any datasets that are not yet ready for viewing (eg, failed the upload step)
    """
    queryset = lz_models.AnalysisInfo.objects.ingested().select_related('owner')
    serializer_class = serializers.GwasSerializer
    permission_classes = (permissions.GwasViewPermission,)
    # Show oldest first, so that people see high quality examples on the homepage. (eventually we could curate)
    ordering = ('created',)

    filterset_class = GwasFilter
    search_fields = ('label', 'study_name', 'pmid')

    def get_queryset(self):
        queryset = super(GwasListView, self).get_queryset()
        modified = queryset.filter(is_public=True)
        if self.request.user.is_authenticated:
            modified |= queryset.filter(owner=self.request.user)
        return modified


class GwasListViewUnprocessed(generics.ListAPIView):
    """
    List all GWAS studies owned by a specific user, *including* those that are pending or failed ingest
    """
    schema = None  # This is a private endpoint for internal use; hide from documentation

    queryset = lz_models.AnalysisInfo.objects.all_active().select_related('owner')
    serializer_class = serializers.GwasSerializerUnprocessed
    permissions = (drf_permissions.IsAuthenticated, permissions.GwasViewPermission)
    ordering = ('-created',)

    def get_queryset(self):
        queryset = super(GwasListViewUnprocessed, self).get_queryset()
        return queryset.filter(owner=self.request.user)


class GwasDetailView(generics.RetrieveAPIView):
    """Metadata describing one particular uploaded GWAS"""
    permission_classes = (permissions.GwasViewPermission,)
    queryset = lz_models.AnalysisInfo.objects.ingested()
    serializer_class = serializers.GwasSerializer

    lookup_field = 'slug'


class GwasRegionView(generics.RetrieveAPIView):
    """
    Fetch the parsed GWAS data (such as from a file) for a specific region

    This is not a JSONAPI endpoint and it does not draw from a database. Therefore, it is intentionally allowed to use
        a different (more concise) format and disables default query param validation/ filtering behavior
    """
    renderer_classes = [drf_renderers.JSONRenderer]
    filter_backends: list = []
    queryset = lz_models.AnalysisInfo.objects.ingested()
    serializer_class = serializers.GwasFileSerializer
    permission_classes = (permissions.GwasViewPermission,)

    lookup_field = 'slug'

    def get_serializer(self, *args, **kwargs):
        """Unique scenario: a single model that returns a list of records"""
        return super(GwasRegionView, self).get_serializer(*args, many=True, **kwargs)

    def get_object(self):
        gwas = super(GwasRegionView, self).get_object()  # External-facing GWAS id given as slug in url
        chrom, start, end = self._query_params()

        if not os.path.isfile(gwas.files.normalized_gwas_path):
            raise drf_exceptions.NotFound

        # We deliberately exclude missing pvalues because this endpoint is primarily aimed at association plots
        reader = guess_gwas_standard(gwas.files.normalized_gwas_path)\
            .add_filter('neg_log_pvalue')

        try:
            return list(reader.fetch(chrom, start, end))
        except ValueError:
            # PySAM will throw a ValueError when tabixing to a chrom not present in the file (but it's ok with an
            #   empty region in a known chromosome)
            # Let's make the behavior the same: no known chromosome = no data for region
            return []

    def _query_params(self) -> ty.Tuple[str, int, int]:
        """
        Specific rules for GWAS retrieval
        - Must specify chrom, start, and end as query params
        - start and end must be integers
        - end > start
        - 0 <= (end - start) <= 500000
        """
        params = self.request.query_params

        chrom = params.get('chrom', None)
        start = params.get('start', None)
        end = params.get('end', None)

        if not (chrom and start and end):
            raise drf_exceptions.ParseError('Must specify "chrom", "start", and "end" as query parameters')

        try:
            start = int(start)
            end = int(end)
        except ValueError:
            raise drf_exceptions.ParseError('"start" and "end" must be integers')

        if end <= start:
            raise drf_exceptions.ParseError('"end" position must be greater than "start"')

        if not (0 <= (end - start) <= settings.LZ_MAX_REGION_SIZE):
            raise drf_exceptions.ParseError(
                f'Cannot handle requested region size. Max allowed is {settings.LZ_MAX_REGION_SIZE}')

        return chrom, start, end

locuszoom_plotting_service/templates/gwas/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete Study{% endblock %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'gwas:overview' gwas.slug %}">Study</a></li>
          <li class="breadcrumb-item active">Delete</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>
          Are you sure you want to delete this study? This will permanently remove your data from the server.
          This operation cannot be un-done.
        </p>

        <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <a class="btn btn-outline-secondary">Go back</a> <input class="btn btn-danger" type="submit" value="Delete"/>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

locuszoom_plotting_service/templates/gwas/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Study Info{% endblock %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'gwas:overview' gwas.slug %}">Study</a></li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h2>Edit Study Data</h2>
        <form method="POST">
          {% csrf_token %}
          {{ form | crispy }}
          <input class="btn btn-success" type="submit" value="Submit"/>
        </form>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12">
        <h2>Potentially destructive actions</h2>
        <form method="post" action="{% url 'gwas:rerun' gwas.slug %}" class="form-horizontal">
          {% csrf_token %}
          <button class="btn btn-warning" type="submit">Re-run ingest step</button>
          <a class="btn btn-warning" href="{% url 'gwas:delete' gwas.slug %}">Delete this study</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

locuszoom_plotting_service/templates/gwas/gwas_region.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Region plot- {{ gwas.label }}{% endblock %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% filter add_token:token %}{% url 'gwas:overview' gwas.slug %}{% endfilter %}">{{ gwas.label }}</a>
          </li>
          <li class="breadcrumb-item active">Region view</li>
        </ol>

        {% if gwas.study_name %}<span class="text-muted">Study: {{ gwas.study_name }}</span><br>{% endif %}
        <span class="text-muted">Build: {{ gwas.build }}</span><br>
        <span class="text-muted">Uploaded by: {{ gwas.owner.display_name }}, {{ gwas.created | date }}</span>
        {% if gwas.is_public %}<span class="badge badge-info">Public</span> {% else %}<span class="badge badge-warning">Private</span>{% endif %}
        {% if gwas.pmid %}<a href="https://www.ncbi.nlm.nih.gov/pubmed/{{gwas.pmid}}" target="_blank" class="badge badge-dark">PubMed</a>{% endif %}
        {% if gwas.owner == request.user %}(<a href="{% url 'gwas:edit' gwas.slug %}">edit</a>)
          {% if not gwas.is_public %}(<a href="{% url 'gwas:share' gwas.slug %}">share</a>){% endif %}
        {% endif %}
      </div>
    </div>

    <div id="app"></div>
  </div>
{% endblock %}

{% block javascript %}
  <script type="application/javascript">
    {#var template_args = JSON.parse(document.getElementById('js-vars').textContent);#}
    window.template_args = {{ js_vars |safe }};
  </script>

  {#  {{ js_vars | json_script: 'js-vars' }}#}
  {#  Define the LocusZoom plot #}
  <script src="{% static 'webpack_bundles/gwas_region.js' %}"></script>
{% endblock %}

locuszoom_plotting_service/templates/gwas/gwas_summary.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Study- {{ gwas.label }}{% endblock %}


{% block css %}
  <style type="text/css">
    .d3-tip {
      line-height: 1.4;
      padding: 12px;
      background: rgba(0, 0, 0, 0.8);
      color: #fff;
      border-radius: 4px;
      pointer-events: none;
    }

    /* Creates a small triangle extender for the tooltip */
    .d3-tip:after {
      display: inline;
      font-size: 10px;
      width: 100%;
      line-height: 1;
      color: rgba(0, 0, 0, 0.8);
      position: absolute;
      pointer-events: none;
    }

    /* Northward tooltips */
    .d3-tip.n:after {
      content: "\25BC";
      margin: -3px 0 0 0;
      top: 100%;
      left: 0;
      text-align: center;
    }

    #manhattan_plot_container {
      min-width: 700px;
    }

    #manhattan_plot_container .axis > path.domain {
      stroke-width: 2px;
      stroke: #666;
      fill: none;
    }

    #manhattan_plot_container .axis g.tick line {
      stroke: #666;
    }

    #qq_plot_container .axis path.domain {
      stroke: black;
      fill: none;
    }

    #qq_plot_container .axis g.tick line {
      stroke: #666;
      opacity: 0.3;
    }

    .pheno-info > p {
      margin-bottom: 0;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    <h1>{{ gwas.label }}</h1>
    <div class="row">
      <div class="col-md-12">
        {% if gwas.study_name %}<span class="text-muted">Study: {{ gwas.study_name }}</span><br>{% endif %}
        <span class="text-muted">Build: {{ gwas.build }}</span><br>
        <span class="text-muted">Uploaded by: {{ gwas.owner.display_name }}, {{ gwas.created | date }}</span>
        {% if gwas.is_public %}<span class="badge badge-info">Public</span> {% else %}<span class="badge badge-warning">Private</span>{% endif %}
        {% if gwas.pmid %}<a href="https://www.ncbi.nlm.nih.gov/pubmed/{{gwas.pmid}}" target="_blank" class="badge badge-dark">PubMed</a>{% endif %}
        {% if gwas.owner == request.user %}(<a href="{% url 'gwas:edit' gwas.slug %}">edit</a>)
          {% if not gwas.is_public %}(<a href="{% url 'gwas:share' gwas.slug %}">share</a>){% endif %}
        {% endif %}
      </div>
    </div>

    {% if gwas.ingest_status == 2 %}
      <div class="row">
        <div class="col-md-12">
          <a class="btn btn-outline-secondary float-right" href="{% filter add_token:token %}{% url 'gwas:gwas-download' gwas.slug %}{% endfilter %}">Download summary statistics</a>
          {%  if request.user == gwas.owner %}
            <a class="btn btn-outline-secondary float-right" href="{% url 'gwas:gwas-ingest-log' gwas.slug %}">Ingest Logs</a>
            <div class="dropdown">
              <button type="button" id="checksumDropdown"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                      class="btn btn-outline-secondary dropdown-toggle float-right">
                Checksum
              </button>
              <div class="dropdown-menu p-1" aria-labelledby="checksumDropdown">
                Uploaded file hash (SHA256):<br>
                <div class="input-group" id="copy-sha256">
                  <input id="copy-value-sha256" type="text" class="form-control"
                         readonly size="15"
                         value="{{ gwas.files.file_sha256.hex }}">
                  <div class="input-group-append">
                    <button id="copy-button-sha256" class="btn btn-outline-info ">Copy</button>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h3>Manhattan Plot</h3>
          <p>
            Click on any peak in the manhattan plot below to jump to a specific LocusZoom region view, or visit the
            <a href="{% filter add_token:token %}{% url 'gwas:region' gwas.slug %}{% endfilter %}">region page</a> to make plots for any region in your dataset
            (with search features for gene, position, or rsid).
          </p>
          <div id="manhattan_plot_container"></div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h3>Top Loci</h3>
          <div id="top-hits-table"></div>
        </div>
      </div>

      <div class="row">
        <div class="pheno-info col-xs-12 col-sm-4 col-md-3 col-lg-3">
          <h3>QQ Plot:</h3>
          <div id="qq_plot_container"></div>
          <p class="gc-control"></p>
          <i>(Genomic Control lambda calculated based on the 50th percentile (median), 10th percentile, 1st percentile,
            and 1/10th of a percentile)</i>
        </div>
      </div>
    {% elif gwas.ingest_status == 0 %}
      This file is still being processed. A notification email will be sent when it is ready.
    {% else %}
      <p>We were unable to process your uploaded GWAS file. Please review the logs for the cause, and contact us
        if you believe the problem is an error.</p>
      {# FIXME: At present, metadata.files is only set at conclusion of a successful upload (tasks.py). This makes it difficult to show the SHA, which lives in the associated "this is the file for a study" record. #}
      {#      <p>You can verify that you uploaded the correct file by comparing the checksum (SHA256):<br>#}
      {#        <span class="text-muted">{{ gwas.files.file_sha256.hex }}</p>#}
      {%  if request.user == gwas.owner %}
        <form method="post" action="{% url 'gwas:rerun' gwas.slug %}" class="form-horizontal">
          {% csrf_token %}
          <a class="btn btn-outline-secondary" href="{% url 'gwas:gwas-ingest-log' gwas.slug %}">Ingest Logs</a>
          <button class="btn btn-warning" type="submit">Re-run ingest step</button>
        </form>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}

{% block javascript %}
  <script type="application/javascript">
    {#var template_args = JSON.parse(document.getElementById('js-vars').textContent);#}
    {# FIXME: Improve JS variable handling for Django 2.1 LTS #}
    window.template_args = {{ js_vars |safe }};

    // Required as hardcoded global reference in PheWeb pheno.js
    window.model = {
      urlprefix: '{% filter add_token:token %}{% url 'gwas:region' gwas.slug %}{% endfilter %}',
      tooltip_underscoretemplate: '<b><%- d.chrom %>:<%- d.pos.toLocaleString() %> <%- (d.ref && d.alt) ? (d.ref + "/" + d.alt) : "" %></b><br>-log<sub>10</sub>(p): <%- d.neg_log_pvalue && (+d.neg_log_pvalue).toFixed(3) %><br>Nearest gene(s): <%- d.nearest_genes && d.nearest_genes.length && d.nearest_genes.map(function(gene) { return gene.symbol; }).join(", ") %>'
    };
    window.pheno = '';

    // For logged in users, show SHA256 and provide a "copy to clipboard" button
    const copyButton = document.querySelector('#copy-button-sha256');
    if (copyButton) {
      copyButton.addEventListener('click', () => {
        document.querySelector('#copy-value-sha256').select();
        document.execCommand('copy');
      });
    }

  </script>

  {% if GOOGLE_ANALYTICS_ID %}
    <script>
      // Track aggregate manhattan plots viewed (across all possible studies) as an event
      gtag('event', 'manhattanview');
    </script>
  {% endif %}

  <script src="{% static 'webpack_bundles/gwas_summary.js' %}"></script>
{% endblock %}

locuszoom_plotting_service/templates/gwas/share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Share this study{% endblock %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'gwas:overview' gwas.slug %}">Study</a></li>
          <li class="breadcrumb-item active">Share</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        {% if gwas.is_public %} {# If the study is public, no "special access" links are needed! #}
          <p>
            This GWAS is already publicly accessible, and can be shared via the following URL:
            <a href="{% url 'gwas:overview' gwas.slug %}">{{ request.scheme }}://{{ request.get_host }}{% url 'gwas:overview' gwas.slug %}</a>.
          </p>
        {% else %}
          <h2>Shareable links</h2>
          <table class="table" id="view-links-list">
            <tr>
              <th>Label</th>
              <th>URL</th>
            </tr>
            {% for link in viewlinks %}
              <tr>
                <td>{% firstof link.label link.created %}</td>
                <td>
                  <div class="input-group" id="copy-controls-{{ forloop.counter }}">
                    <input type="text" id="copy-value-{{ forloop.counter }}"  class="form-control" readonly
                           value="{{ request.scheme }}://{{ request.get_host }}{{ link.get_absolute_url }}">
                    <div class="input-group-append">
                      <button id="copy-button-{{ forloop.counter }}" class="btn btn-outline-info">Copy</button>
                    </div>
                  </div>
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="2">There are no shareable links yet.</td>
              </tr>
            {% endfor %}
          </table>


          <h2>Create a shareable link</h2>
          <p>
            Generate a secret link that can be used to share your private studies only with trusted collaborators.
            Only you can see this page or create new shareable links.
          </p>

          <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <input class="btn btn-success" type="submit" value="Create"/>
          </form>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

{% block javascript %}
<script type="application/javascript">
   document.querySelectorAll('div[id^=copy-controls]').forEach(function (row) {
       // Connect each "copy value" button to the corresponding text field
       var textbox = row.querySelector('[id^=copy-value]');
       var button = row.querySelector('[id^=copy-button]');
       button.addEventListener('click', function() {
           textbox.select();
           document.execCommand('copy');
       });
   })
</script>
{% endblock %}

locuszoom_plotting_service/templates/gwas/upload.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Upload your data{% endblock %}

{% block css %}
  <style> {# Hack: hide this form field because we will set parser options via vue modal #}
    #div_id_fileset-parser_options {
      display: none;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="container">
  <h2>Upload Summary Statistics</h2>
    <div class="row">
      <div class="col-md-12">
        <p>
          We accept <em>tab-delimited</em> files in either .txt or .gz formats. Your summary statistics should be
          sorted via chromosome and position before uploading. In general, if your data can be tabixed, there is a
          good chance that our server can accept and parse the contents. For best results, make sure that your file
          contains the following information for each variant: chromosome, position, reference and alt alleles, and
          p-value (or -log<sub>10</sub> p).
        </p>
        <p>
          We limit uploads to ~1 GB max filesize. If you have a large file, it may take a long time to upload on a
          slow connection. For very large datasets, consider using
          <a href="https://github.com/abought/locuszoom-tabix">LocalZoom</a> to make region plots from a tabixed file,
          without uploading.
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <form action="{% url 'gwas:upload' %}" enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ form.metadata | crispy }}
          {{ form.fileset | crispy }}
          <input class="btn btn-success" type="submit" value="Submit" />
        </form>
      </div>
    </div>

    {#  For options modal and future features #}
    <div id="vue-app"></div>
  </div>
{% endblock %}

{%  block javascript %}
  <script src="{% static 'webpack_bundles/gwas_upload.js' %}"></script>
{% endblock %}